[package]
name = "rc-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
filetime = "0.2"
tracing.workspace = true

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29", default-features = false, features = ["fs", "process", "signal", "user"] }
